default:
  tags:
    - kubernetes

stages:
  - build
  - deploy
  - publish

variables:
  BUILD_DIR1: build1
  BUILD_DIR2: build2
  TARGET_DIR: /docs/_build/

.build:base:
  stage: build
  image: ${HARBOR_PROXY_DOCKER_HUB}/library/python:3.9
  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PIP_ROOT_USER_ACTION: ignore
  cache:
    key:
      files:
        - requirements.txt
    paths:
      - .cache/pip
  before_script:
    - |
      # Create .netrc for Nexus authentication
      NEXUS_HOSTNAME="${NEXUS_HOST#*://}"
      echo "machine $NEXUS_HOSTNAME login $NEXUS_USERNAME password $NEXUS_PASSWORD" >"$HOME/.netrc"
      chmod 600 "$HOME/.netrc"
      export PIP_INDEX_URL=${NEXUS_PYPI_GROUP_PUBLIC_SIMPLE}
    - |
      # Install requirements
      pip install -q --log pip_requirements.log --progress-bar off --use-deprecated=legacy-resolver -r requirements.txt || {
        cat pip_requirements.log 2>/dev/null || true
        exit 1
      }
  script:
    - |
      # Build
      rm -rf $BUILD_DIR
      sphinx-build -b html $SOURCE_DIR $BUILD_DIR/html
  artifacts:
    paths:
      - $BUILD_DIR/html

build_v1:
  extends:
    - .build:base
  variables:
    SOURCE_DIR: source-lk-v1
    BUILD_DIR: $BUILD_DIR1
  rules:
    - changes:
        - source-lk-v1/**/*

build_v2:
  extends:
    - .build:base
  variables:
    SOURCE_DIR: source-lk-v2
    BUILD_DIR: $BUILD_DIR2
  rules:
    - changes:
        - source-lk-v2/**/*

deploy_test_v1:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$TEST_LK_V1_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $TEST_LK_V1_SERVER >> ~/.ssh/known_hosts
  script:
    - apk add --no-cache rsync
    - rsync -avz --delete $BUILD_DIR1/html/ $USER@$TEST_LK_V1_SERVER:$TARGET_DIR
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
      changes:
        - source-lk-v1/**/*

deploy_prod_v1:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$PROD_LK_V1_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $PROD_LK_V1_SERVER >> ~/.ssh/known_hosts
  script:
    - apk add --no-cache rsync
    - rsync -avz --delete $BUILD_DIR1/html/ $USER@$PROD_LK_V1_SERVER:$TARGET_DIR
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - source-lk-v1/**/*

deploy_test_v2:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$TEST_LK_V2_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $TEST_LK_V2_SERVER >> ~/.ssh/known_hosts
  script:
    - apk add --no-cache rsync
    - rsync -avz --delete $BUILD_DIR2/html/ $USER@$TEST_LK_V2_SERVER:$TARGET_DIR
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
      changes:
        - source-lk-v2/**/*

deploy_prod_v2:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$PROD_LK_V2_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $PROD_LK_V2_SERVER >> ~/.ssh/known_hosts
  script:
    - apk add --no-cache rsync
    - rsync -avz --delete $BUILD_DIR2/html/ $USER@$PROD_LK_V2_SERVER:$TARGET_DIR
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - source-lk-v2/**/*

publish:
  stage: publish
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - echo "Publishing contents to GitHub"
    - git config --global user.email "github@rapporto.ru"
    - git config --global user.name "Rapporto AutoDeploy"
    - git clone --depth 1 https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git publish_directory
    - cp -r source-lk-v1 publish_directory/
    - cp -r source-lk-v2 publish_directory/
    - cp -r requirements.txt publish_directory/
    - cd publish_directory
    - git add .
    - git commit -m "Publish contents"
    - git push origin main
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  dependencies:
    - deploy_prod_v1
    - deploy_prod_v2
