include:
  - project: rapporto/devops/gitlab/ci-templates
    ref: main
    file: Jobs/_global.gitlab-ci.yml

stages:
  - build
  - deploy
  - publish

variables:
  BUILD_DIR1: build1
  BUILD_DIR2: build2

build_v1:
  extends:
    - .build:base
  variables:
    SOURCE_DIR: source-lk-v1
    BUILD_DIR: $BUILD_DIR1
  rules:
    - changes:
        - source-lk-v1/**/*

build_v2:
  extends:
    - .build:base
  variables:
    SOURCE_DIR: source-lk-v2
    BUILD_DIR: $BUILD_DIR2
  rules:
    - changes:
        - source-lk-v2/**/*

deploy_test_v1:
  extends:
    - .deploy:base
  variables:
    SSH_KEY_VAR: $TEST_LK_V1_SSH_KEY
    SERVER: $TEST_LK_V1_SERVER
    BUILD_DIR: $BUILD_DIR1
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
      changes:
        - source-lk-v1/**/*

deploy_test_v2:
  extends:
    - .deploy:base
  variables:
    SSH_KEY_VAR: $TEST_LK_V2_SSH_KEY
    SERVER: $TEST_LK_V2_SERVER
    BUILD_DIR: $BUILD_DIR2
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
      changes:
        - source-lk-v2/**/*

deploy_prod_v1:
  extends:
    - .deploy:base
  variables:
    SSH_KEY_VAR: $PROD_LK_V1_SSH_KEY
    SERVER: $PROD_LK_V1_SERVER
    BUILD_DIR: $BUILD_DIR1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - source-lk-v1/**/*

deploy_prod_v2:
  extends:
    - .deploy:base
  variables:
    SSH_KEY_VAR: $PROD_LK_V2_SSH_KEY
    SERVER: $PROD_LK_V2_SERVER
    BUILD_DIR: $BUILD_DIR2
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - source-lk-v2/**/*

publish:
  stage: publish
  image: alpine:latest
  script:
    - |
      # Publish to GitHub
      apk add --no-cache git
      git config --global user.email "github@rapporto.ru"
      git config --global user.name "Rapporto AutoDeploy"
      git clone --depth 1 https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git publish_directory
      cp -r source-lk-v1 publish_directory/
      cp -r source-lk-v2 publish_directory/
      cp -r requirements.txt publish_directory/
      cd publish_directory
      git add .
      git commit -m "Publish contents"
      git push origin main
  dependencies:
    - deploy_prod_v1
    - deploy_prod_v2
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.build:base:
  stage: build
  image: ${HARBOR_PROXY_DOCKER_HUB}/library/python:3.9
  variables:
    PIP_INDEX_URL: $NEXUS_PYPI_GROUP_PUBLIC_SIMPLE
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PIP_ROOT_USER_ACTION: ignore
  cache:
    key:
      files:
        - requirements.txt
    paths:
      - $PIP_CACHE_DIR
  script:
    - !reference ['.global-snippets', create-nexus-netrc]
    - |
      # Install requirements
      pip install -q --log pip_requirements.log --progress-bar off --use-deprecated=legacy-resolver -r requirements.txt || {
        cat pip_requirements.log 2>/dev/null || true
        exit 1
      }
    - |
      # Build
      rm -rf $BUILD_DIR
      sphinx-build -b html $SOURCE_DIR $BUILD_DIR/html
  artifacts:
    expire_in: 7 days
    paths:
      - $BUILD_DIR/html

.deploy:base:
  stage: deploy
  image: alpine:latest
  variables:
    DEPLOY_TARGET_DIR: /docs/_build/
  script:
    - |
      # Deploy
      apk add --no-cache openssh-client rsync
      mkdir -p "$HOME/.ssh"
      echo "$SSH_KEY_VAR" >"$HOME/.ssh/id_rsa"
      chmod 600 "$HOME/.ssh/id_rsa"
      ssh-keyscan -H $SERVER >>"$HOME/.ssh/known_hosts"
      rsync -avz --delete $BUILD_DIR/html/ $USER@$SERVER:$DEPLOY_TARGET_DIR
